@GameAPIs_HostAddress=https://localhost:7011
@ContentType = application/json

### Root Route

GET {{GameAPIs_HostAddress}}/

### Get All Games
GET {{GameAPIs_HostAddress}}/games

### Valid Game ID
GET {{GameAPIs_HostAddress}}/games/7dddd33b-fa28-49a9-8dfb-a145d800be0c


### Invalid Game ID
GET {{GameAPIs_HostAddress}}/games/7dddd33b-fa28-49a9-8dfb-b245d800be0c


### Create Game
POST {{GameAPIs_HostAddress}}/games
Content-Type: {{ContentType}}

{
    "name": "Test Game",
    "genre": "Action",
    "price": 19.99,
    "releaseDate": "1992-07-15"
}

### Update Game
PUT {{GameAPIs_HostAddress}}/games/954aaaad-fcf4-4ed2-9106-eee20fff87d5
Content-Type: {{ContentType}}

{
    "name": "Test Game Updated",
    "genre": "Family and Kids",
    "price": 7.97,
    "releaseDate": "2011-11-18"
}

### Delete Game
DELETE {{GameAPIs_HostAddress}}/games/954aaaad-fcf4-4ed2-9106-eee20fff87d5